name: Build docker

on:
  workflow_call:
    inputs:
      os:
        description: Operation system to build artifact for.
        required: true
        type: string 
      release:
        description: Number of released version. Not required.
        required: false
        type: string 

env:
  REGISTRY_IMAGE: takecontrolorg/sync_server

jobs:
  prepare-docker:
    runs-on: ubuntu-latest
    outputs:
      matrix_arch_list: ${{ steps.platforms.outputs.architectures }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create architectures
        id: platforms
        run: |
          echo "platforms=$(docker buildx bake sync_server_${{ inputs.os }} --print | jq -cr '.target."sync_server_${{ inputs.os }}".platforms')" >>${GITHUB_OUTPUT}
          echo "architectures=$(platforms//${{ inputs.os }}///')" >>${GITHUB_OUTPUT}
      - name: Show architectures
        run: |
          echo ${{ steps.platforms.outputs.architectures }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
              # branch event
              type=ref,event=branch
              # tag event
              type=ref,event=tag
              # pull request event
              type=ref,event=pr
      - name: Rename meta bake definition file
        run: |
          mv "${{ steps.meta.outputs.bake-file }}" "/tmp/bake-meta-${{ inputs.os }}.json"
      - name: Upload meta bake definition
        uses: actions/upload-artifact@v4
        with:
          name: bake-meta-${{ inputs.os }}
          path: /tmp/bake-meta-${{ inputs.os }}.json
          if-no-files-found: error
          retention-days: 1

  build:
    runs-on: ${{ inputs.os != 'linux' && inputs.os || 'ubuntu' }}-latest
    needs: prepare-docker
    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJson(needs.prepare-docker.outputs.matrix_arch_list) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: sync_server${{ inputs.release}}-${{ inputs.os }}-${{ matrix.architecture }}
          path: bin/
      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta-${{ inputs.os }}
          path: /tmp
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: bake
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            /tmp/bake-meta-${{ inputs.os }}.json
          targets: "sync_server_${{ inputs.os }}"
          set: |
            *.tags=
            *.platform=${{ inputs.os }}/${{ matrix.architecture }}
            *.output=type=image,"name=${{ env.REGISTRY_IMAGE }}",push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ fromJSON(steps.bake.outputs.metadata)[format('sync_server_{0}', inputs.os) ]['containerimage.digest'] }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.os }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-tags:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta-${{ inputs.os }}
          path: /tmp
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          name: digests-${{ inputs.os }}
          path: /tmp/digests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.target."docker-metadata-action".tags | map(select(startswith("${{ env.REGISTRY_IMAGE }}")) | "-t " + .) | join(" ")' /tmp/bake-meta-${{ inputs.os }}.json) \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:$(jq -r '.target."docker-metadata-action".args.DOCKER_META_VERSION' /tmp/bake-meta-${{ inputs.os }}.json)