name: Sync Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  GO_VERSION: '1.21'

jobs:
  build_and_tests:
    name: Test sync
    secrets: inherit
    with:
      go_version: '1.21'
      upload: true
    uses: ./.github/workflows/tests.yml

  build-docker-linux:
    name: Docker image
    needs: 
      - build_and_tests
    secrets: inherit
    with:
      os: linux
    uses: ./.github/workflows/docker.yml

  

