# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: SYNC_STORAGE_PATH=${{ vars.SYNC_STORAGE_PATH }} bash -c 'go list ./... | grep -v vendor | xargs -n1 go test -timeout=3s'
