name: Sync Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}
  GO_VERSION: '1.21'

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... 

  build-artifacts:
    name: Build and upload artifacts
    needs: build_and_tests
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    with:
      os: '["linux"]'
      architectures: '["amd64", "arm64"]'
      go_version: '1.21'

  build-docker:
    name: Build docker
    needs: 
      - build_and_tests
      - build-artifacts
    secrets: inherit
    with:
      os: linux
    uses: ./.github/workflows/docker.yml

