name: Sync Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}
jobs:
  SyncServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build artifacts
      run: env GOOS=linux GOARCH=amd64 go build main.go -o bin\ 
      
    - name: Upload SyncServer
      uses: actions/upload-artifact@v3
      with:
        name: sync_server
        path: bin/