name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}

jobs:
  build_and_tests:
    name: Test sync
    secrets: inherit
    with:
      go_version: ${{ vars.GO_VERSION }}
    uses: ./.github/workflows/w_tests.yml



