name: Sync Server Test

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}

jobs:
  build_and_tests:
    name: Test sync
    secrets: inherit
    with:
      go_version: ${{ vars.GO_VERSION }}
    uses: ./.github/workflows/tests.yml

  #To be removed after tests
  build-artifacts:
    name: Artifacts
    needs: build_and_tests
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    with:
      os: '["linux"]'
      architectures: '["amd64", "arm64"]'
      go_version: ${{ vars.GO_VERSION }}

  build-docker-linux:
    name: Docker image
    needs: 
      - build_and_tests
      - build-artifacts
    secrets: inherit
    with:
      os: linux
    uses: ./.github/workflows/docker.yml


