name: Sync Server Test

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || (github.workflow && github.run_id) }}
  cancel-in-progress: true
  
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}
  GO_VERSION: '1.21'

jobs:
  build_and_tests:
    name: Test sync
    secrets: inherit
    with:
      go_version: '1.21'
    uses: ./.github/workflows/tests.yml


