name: Pre-release Sync Server
# This workflow is triggered when a new tag is published
# `git tag v0.0.1alpha`
# `git push --tags`
# If the tag already exists, use this commanf to delete it `git tag -d v0.0.1alpha`
on:
  push:
    tags:
      - 'v*'

permissions: write-all
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}

jobs:
    release:
      if: contains(github.ref, 'tags/v')
      runs-on: ubuntu-latest
      outputs: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        v_num:  ${{ steps.version.outputs.number }}
    
      steps:
        - uses: actions/checkout@v3

        - name: Get version number
          id: version
          run: |
            echo "tag_ref=$(echo '${{ github.ref }}' | cut -d '/' -f 3)"
            echo "number=$tag_ref" >>${GITHUB_OUTPUT}
        - name: Show version number
          run: |
            echo ${{ steps.version.outputs.number }}
     
        - name: Build Cross-Platform
          uses: crazy-max/ghaction-xgo@v3
          with:
            xgo_version: latest
            go_version: 1.21
            dest: build
            prefix: sync_server-${{ steps.version.outputs.number }}
            targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
            v: true
            x: false
            race: false
            ldflags: -s -w
            buildmode: default
            trimpath: true  

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: false
            prerelease: true
 
               
        - name: Upload Linux Asset
          uses: glentiki/xbin-release-action@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            assets_path: ./build
        

    build-docker-linux:
      name: Docker image
      needs: release
      secrets: inherit
      with:
        os: linux
        release:  -${{ needs.release.outputs.v_num }}
      uses: ./.github/workflows/docker.yml
            