name: Release Draft Sync Server

on:
  push:
    tags:
      - 'v*'
permissions: write-all
jobs:
    Release:
      if: contains(github.ref, 'tags/v')
      runs-on: ubuntu-latest
      outputs: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    
      steps:
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: Tag ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false
      
        - name: Download All Artifacts
          uses: actions/download-artifact@v2
         
        - name: Upload Linux Asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bin/
            asset_name: sync_server
            asset_content_type: application/zip
        