name: Tests

on:
  workflow_call:
    inputs:
      go_version:
        description: Go version to be used for the build.
        required: true
        type: string
      upload:
          description: If true builds and uploads artifact.
          required: false
          type: boolean        
env:
  SYNC_STORAGE_PATH: ${{ vars.SYNC_STORAGE_PATH }}
  SYNC_SERVER_PORT: ${{ vars.SYNC_SERVER_PORT }}

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... 

    - name: Build artifacts
      run: go build -o bin/

    - name: Upload SyncServer
      uses: actions/upload-artifact@v3
      with:
        name: sync_server-linux-amd64
        path: bin/sync_server